name: fl_chart
description: chart custom
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_drawing: ^0.5.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.3
  pedantic: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


